services:

  database:
    image: "postgres:12"
    platform: linux/amd64
    environment:
      POSTGRES_USER: omero
      POSTGRES_DB: omero
      POSTGRES_PASSWORD: omero
    networks:
      - omero
    volumes:
      - "database:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  omeroserver:
    # This container uses the tag for the latest server release of OMERO 5
    # To upgrade to the next major release, increment the major version number
    depends_on:
      - database
    build: test/omero-server
    platform: linux/amd64
    environment:
      CONFIG_omero_client_icetransports: ssl,wss
      CONFIG_omero_db_host: database
      CONFIG_omero_db_user: omero
      CONFIG_omero_db_pass: omero
      CONFIG_omero_db_name: omero
      CONFIG_omero_policy_binary__access: +read,+write,+image,+plate
      CONFIG_omero_glacier2_IceSSL_Ciphers: "HIGH:!DH"
      ROOTPASS: omero

    networks:
      - omero
    ports:
      - "6063:4063"
      - "6064:4064"
      - "8443:8443"
    volumes:
      - "omero:/OMERO"

  omeroweb:
    depends_on:
      - omeroserver
    build: test/omero-web
    platform: linux/amd64
    environment:
      OMEROHOST: omeroserver
      OMEROWEB_GUNICORN_TIMEOUT: 600
    volumes:
      - type: bind
        source: ./omero_metrics
        target: /opt/omero/web/venv3/lib/python3.10/site-packages/omero_metrics
      - type: bind
        source: ./config_files/config.omero
        target: /opt/omero/web/config/config.omero
    networks:
      - omero
    ports:
      - "5080:4080"


networks:
  omero:

volumes:
  database:
  omero: